# ===================================
#  List Behavior Config
# ===================================

title: Manage Users
list: @/plugins/rainlab/user/models/user/columns.yaml
modelClass: RainLab\User\Models\User
recordUrl: rainlab/user/users/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showCheckboxes: yes

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



