# ===================================
#  List Behavior Config
# ===================================

title: rainlab.user::lang.users.list_title
list: ~/plugins/rainlab/user/models/user/columns.yaml
modelClass: RainLab\User\Models\User
recordUrl: rainlab/user/users/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showCheckboxes: true
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



