# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/rainlab/user/models/userlog/columns-global.yaml

# Model Class name
modelClass: RainLab\User\Models\UserLog

# List Title
title: Manage Timelines

# Link URL for each record
# recordUrl: rainlab/user/timelines/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 100

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: false

# Displays the sorting link on each column
showSorting: false

# Default sorting column
defaultSort:
    column: created_at
    direction: desc

# Display checkboxes next to each record
showCheckboxes: false

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
