# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: rainlab.user::lang.location.label

# Model Form Field configuration
form: ~/plugins/rainlab/user/models/country/fields.yaml

# Model Class name
modelClass: RainLab\User\Models\Country

# Default redirect location
defaultRedirect: rainlab/user/locations

# Create page
create:
    title: rainlab.user::lang.location.create_title
    redirect: rainlab/user/locations/update/:id
    redirectClose: rainlab/user/locations

# Update page
update:
    title: rainlab.user::lang.location.update_title
    redirect: rainlab/user/locations
    redirectClose: rainlab/user/locations

# Preview page
preview:
    title: rainlab.user::lang.location.preview_title
