# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: @/plugins/rainlab/user/models/country/columns.yaml

# Model Class name
modelClass: RainLab\User\Models\Country

# List Title
title: Manage Locations

# Link URL for each record
recordUrl: rainlab/user/locations/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Default sorting column
defaultSort:
    column: name
    direction: asc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

# Filter widget configuration
filter: config_filter.yaml