# ===================================
#  Relation Behavior Config
# ===================================

states:
    label: rainlab.user::lang.locations.state
    list: ~/plugins/rainlab/user/models/state/columns.yaml
    form: ~/plugins/rainlab/user/models/state/fields.yaml
    # toolbar:
    #     buttons: relation_toolbar